package com.gates.dao;

import com.gates.entity.WOperator;

public interface WOperatorDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_operator
     *
     * @mbggenerated Wed Jan 31 17:05:03 CST 2018
     */
    int insert(WOperator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_operator
     *
     * @mbggenerated Wed Jan 31 17:05:03 CST 2018
     */
    int insertSelective(WOperator record);
}