package com.gates.entity;

import java.util.Date;

public class WOperator {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_operator.ID
     *
     * @mbggenerated Wed Jan 31 17:05:03 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_operator.ACCOUNT
     *
     * @mbggenerated Wed Jan 31 17:05:03 CST 2018
     */
    private String account;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_operator.PASSWORD
     *
     * @mbggenerated Wed Jan 31 17:05:03 CST 2018
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_operator.NICK_NAME
     *
     * @mbggenerated Wed Jan 31 17:05:03 CST 2018
     */
    private String nickName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_operator.CREATE_TIME
     *
     * @mbggenerated Wed Jan 31 17:05:03 CST 2018
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_operator.ID
     *
     * @return the value of w_operator.ID
     *
     * @mbggenerated Wed Jan 31 17:05:03 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_operator.ID
     *
     * @param id the value for w_operator.ID
     *
     * @mbggenerated Wed Jan 31 17:05:03 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_operator.ACCOUNT
     *
     * @return the value of w_operator.ACCOUNT
     *
     * @mbggenerated Wed Jan 31 17:05:03 CST 2018
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_operator.ACCOUNT
     *
     * @param account the value for w_operator.ACCOUNT
     *
     * @mbggenerated Wed Jan 31 17:05:03 CST 2018
     */
    public void setAccount(String account) {
        this.account = account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_operator.PASSWORD
     *
     * @return the value of w_operator.PASSWORD
     *
     * @mbggenerated Wed Jan 31 17:05:03 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_operator.PASSWORD
     *
     * @param password the value for w_operator.PASSWORD
     *
     * @mbggenerated Wed Jan 31 17:05:03 CST 2018
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_operator.NICK_NAME
     *
     * @return the value of w_operator.NICK_NAME
     *
     * @mbggenerated Wed Jan 31 17:05:03 CST 2018
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_operator.NICK_NAME
     *
     * @param nickName the value for w_operator.NICK_NAME
     *
     * @mbggenerated Wed Jan 31 17:05:03 CST 2018
     */
    public void setNickName(String nickName) {
        this.nickName = nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_operator.CREATE_TIME
     *
     * @return the value of w_operator.CREATE_TIME
     *
     * @mbggenerated Wed Jan 31 17:05:03 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_operator.CREATE_TIME
     *
     * @param createTime the value for w_operator.CREATE_TIME
     *
     * @mbggenerated Wed Jan 31 17:05:03 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}