package com.gates.entity;

import java.util.Date;

public class WQrcode {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_qrcode.ID
     *
     * @mbggenerated Wed Jan 31 17:05:03 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_qrcode.SCENE_ID
     *
     * @mbggenerated Wed Jan 31 17:05:03 CST 2018
     */
    private Long sceneId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_qrcode.SCENE_STR
     *
     * @mbggenerated Wed Jan 31 17:05:03 CST 2018
     */
    private String sceneStr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_qrcode.ACTION_TYPE
     *
     * @mbggenerated Wed Jan 31 17:05:03 CST 2018
     */
    private Integer actionType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_qrcode.TICKET
     *
     * @mbggenerated Wed Jan 31 17:05:03 CST 2018
     */
    private String ticket;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_qrcode.URL
     *
     * @mbggenerated Wed Jan 31 17:05:03 CST 2018
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_qrcode.ACCOUNT
     *
     * @mbggenerated Wed Jan 31 17:05:03 CST 2018
     */
    private String account;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_qrcode.AWARD
     *
     * @mbggenerated Wed Jan 31 17:05:03 CST 2018
     */
    private String award;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_qrcode.STATUS
     *
     * @mbggenerated Wed Jan 31 17:05:03 CST 2018
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_qrcode.CREATE_TIME
     *
     * @mbggenerated Wed Jan 31 17:05:03 CST 2018
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_qrcode.ID
     *
     * @return the value of w_qrcode.ID
     *
     * @mbggenerated Wed Jan 31 17:05:03 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_qrcode.ID
     *
     * @param id the value for w_qrcode.ID
     *
     * @mbggenerated Wed Jan 31 17:05:03 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_qrcode.SCENE_ID
     *
     * @return the value of w_qrcode.SCENE_ID
     *
     * @mbggenerated Wed Jan 31 17:05:03 CST 2018
     */
    public Long getSceneId() {
        return sceneId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_qrcode.SCENE_ID
     *
     * @param sceneId the value for w_qrcode.SCENE_ID
     *
     * @mbggenerated Wed Jan 31 17:05:03 CST 2018
     */
    public void setSceneId(Long sceneId) {
        this.sceneId = sceneId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_qrcode.SCENE_STR
     *
     * @return the value of w_qrcode.SCENE_STR
     *
     * @mbggenerated Wed Jan 31 17:05:03 CST 2018
     */
    public String getSceneStr() {
        return sceneStr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_qrcode.SCENE_STR
     *
     * @param sceneStr the value for w_qrcode.SCENE_STR
     *
     * @mbggenerated Wed Jan 31 17:05:03 CST 2018
     */
    public void setSceneStr(String sceneStr) {
        this.sceneStr = sceneStr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_qrcode.ACTION_TYPE
     *
     * @return the value of w_qrcode.ACTION_TYPE
     *
     * @mbggenerated Wed Jan 31 17:05:03 CST 2018
     */
    public Integer getActionType() {
        return actionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_qrcode.ACTION_TYPE
     *
     * @param actionType the value for w_qrcode.ACTION_TYPE
     *
     * @mbggenerated Wed Jan 31 17:05:03 CST 2018
     */
    public void setActionType(Integer actionType) {
        this.actionType = actionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_qrcode.TICKET
     *
     * @return the value of w_qrcode.TICKET
     *
     * @mbggenerated Wed Jan 31 17:05:03 CST 2018
     */
    public String getTicket() {
        return ticket;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_qrcode.TICKET
     *
     * @param ticket the value for w_qrcode.TICKET
     *
     * @mbggenerated Wed Jan 31 17:05:03 CST 2018
     */
    public void setTicket(String ticket) {
        this.ticket = ticket;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_qrcode.URL
     *
     * @return the value of w_qrcode.URL
     *
     * @mbggenerated Wed Jan 31 17:05:03 CST 2018
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_qrcode.URL
     *
     * @param url the value for w_qrcode.URL
     *
     * @mbggenerated Wed Jan 31 17:05:03 CST 2018
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_qrcode.ACCOUNT
     *
     * @return the value of w_qrcode.ACCOUNT
     *
     * @mbggenerated Wed Jan 31 17:05:03 CST 2018
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_qrcode.ACCOUNT
     *
     * @param account the value for w_qrcode.ACCOUNT
     *
     * @mbggenerated Wed Jan 31 17:05:03 CST 2018
     */
    public void setAccount(String account) {
        this.account = account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_qrcode.AWARD
     *
     * @return the value of w_qrcode.AWARD
     *
     * @mbggenerated Wed Jan 31 17:05:03 CST 2018
     */
    public String getAward() {
        return award;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_qrcode.AWARD
     *
     * @param award the value for w_qrcode.AWARD
     *
     * @mbggenerated Wed Jan 31 17:05:03 CST 2018
     */
    public void setAward(String award) {
        this.award = award;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_qrcode.STATUS
     *
     * @return the value of w_qrcode.STATUS
     *
     * @mbggenerated Wed Jan 31 17:05:03 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_qrcode.STATUS
     *
     * @param status the value for w_qrcode.STATUS
     *
     * @mbggenerated Wed Jan 31 17:05:03 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_qrcode.CREATE_TIME
     *
     * @return the value of w_qrcode.CREATE_TIME
     *
     * @mbggenerated Wed Jan 31 17:05:03 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_qrcode.CREATE_TIME
     *
     * @param createTime the value for w_qrcode.CREATE_TIME
     *
     * @mbggenerated Wed Jan 31 17:05:03 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}